spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/boog-ai?useSSL=false&characterEncoding=utf8

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false



sa-token.is-read-cookie=false
sa-token.is-read-body=false
sa-token.is-write-header=false
sa-token.is-print=false
sa-token.token-name=Authorization
sa-token.token-prefix=Bearer
sa-token.timeout=86400
sa-token.active-timeout=-1
sa-token.is-concurrent=true
sa-token.is-share=true
sa-token.token-style=random-128
sa-token.is-log=false
sa-token.jwt-secret-key=jonsanme

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.banner=false
spring.main.banner-mode=off